### ISSUE TITLE
Targeting Assembly-CSharp and Assembly-CSharp-firstpass

### ISSUE THREAD

**Issue by fireundubh** [SonicZentropy/TyrannyMod.pw#1]
In `TyrannyPatchInfo.cs`, `GetTargetFile()` returns either `FileInfo` for `Assembly-CSharp.dll` or `Assembly-CSharp-firstpass.dll`. Does this matter? What if you have mods targeting both?

**Comment by SonicZentropy** [comment]
No longer maintaining my version, feel free to fork and update yours though!
