### ISSUE TITLE
Switching repo to use Patchwork as submodule

### ISSUE THREAD

**Issue by fireundubh** [SonicZentropy/TyrannyMod.pw#2]
> It also has a bugfix in the Patchwork framework that crashed Tyranny. Once Patchwork merges my pull req, this repo can switch to using it as a submodule instead of duplicating it.

Patchwork merged your pull request: https://github.com/GregRos/Patchwork/commit/1bc6e08416e36dcbb16d4f91479a065c81515fe0

**Comment by SonicZentropy** [comment]
No longer maintaining my version, feel free to fork and update yours though!
